language: node_js
node_js:
  - "4.5"
before_install:
  - npm install -g grunt-cli
  - npm install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - grunt # check the full build
  - grunt karma:sauce
notifications:
  email: false
sudo: false

addons:
  sauce_connect: true
