language: node_js
node_js:
  - "10"
before_install:
  - npm install

script:
  - npm run build # check the full build
  - npm run test:eslint
  - npm run test
notifications:
  email: false
sudo: false
