language: node_js
node_js:
  - "10"
before_install:
  - npm install

script:
  - npm run build # check the full build
  - karma start test/_karma.conf-sauce.js
notifications:
  email: false
sudo: false

addons:
  sauce_connect: true
